export {
    // General UI
    Menu, X, Bell, LogOut, User, User as UserIcon, ChevronDown, Plus, Plus as PlusIcon, Edit, Edit as EditIcon, Trash, Copy, Copy as CopyIcon, Share2, Share2 as Share2Icon,
    Send, Send as SendIcon, Download, Download as DownloadIcon, Save, Save as SaveIcon, Link, Link as LinkIcon, Search, Search as SearchIcon, Filter, Info,
    RefreshCw as RefreshCwIcon,
    XCircle as XCircleIcon,
    CheckCircle as CheckCircleIcon,
    AlertTriangle as AlertTriangleIcon,
    Info as InfoIcon,
    Check,

    // Sidebar & Pages
    LayoutDashboard,
    Users,
    Users as UsersIcon,
    Briefcase,
    Briefcase as BriefcaseIcon,
    FileText,
    FileText as FileTextIcon,
    DollarSign,
    DollarSign as DollarSignIcon,
    MessageSquare,
    MessageSquare as MessageSquareIcon,
    FileSignature,
    FileSignature as FileSignatureIcon,
    Clock,
    Clock as ClockIcon,
    BarChart2,
    Book,
    Book as BookIcon,
    Settings,
    Settings as SettingsIcon,
    Sparkles,
    Sparkles as SparklesIcon,
    TrendingUp,
    TrendingUp as TrendingUpIcon,
    ListTodo,
    BrainCircuit as BrainCircuitIcon,
    Zap,
    Zap as ZapIcon,
    Shield,
    Shield as ShieldIcon,
    Star as StarIcon,
    Award as AwardIcon,
    
    // Specific
    Target,
    Target as TargetIcon,
    Phone as PhoneIcon,
    Mail as MailIcon,
    ClipboardList as ClipboardListIcon,
    Repeat as RepeatIcon,
    Signature as SignatureIcon,
    GitBranch,
    Calendar,
    Pause,
    Play,
    UserPlus,
    Trash2,
    Trash2 as TrashIcon
} from 'lucide-react';